import './app/game'
/*import './app/sound'*/
import './styles/perspective.css'
import './styles/debug.css'
import './styles/ui.css'
import './styles/game.css'
import './styles/entities/hero.css'
import './styles/entities/entities.css'
import './styles/entities/backdrop.css'